# Generated by Django 4.0.1 on 2022-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_ID', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Photo', models.URLField()),
                ('Nationality', models.CharField(max_length=100)),
                ('Flag', models.URLField(max_length=400)),
                ('Overall', models.IntegerField()),
                ('Potential', models.IntegerField()),
                ('Club', models.CharField(max_length=100)),
                ('Club_Logo', models.URLField(max_length=400)),
                ('Value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
    ]
