# Generated by Django 4.0.1 on 2022-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Player_ID',
            field=models.CharField(max_length=10),
        ),
    ]
