# Generated by Django 4.0.1 on 2022-02-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_alter_players_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='Club_Logo',
            new_name='ClubLogo',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='Player_ID',
            new_name='PlayerID',
        ),
    ]
