# Generated by Django 4.0.1 on 2022-02-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_remove_players_clublogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='PlayerID',
            new_name='Player',
        ),
    ]
