# Generated by Django 4.0.1 on 2022-02-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0006_remove_players_player'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='players',
            table=None,
        ),
    ]
